
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module top (

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// LED //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7
);

  logic [31:0] io2;

  hexdriver hd0 (.val(io2[3:0]), .HEX(HEX0));
  hexdriver hd1 (.val(io2[7:4]), .HEX(HEX1));
  hexdriver hd2 (.val(io2[11:8]), .HEX(HEX2));
  hexdriver hd3 (.val(io2[15:12]), .HEX(HEX3));
  hexdriver hd4 (.val(io2[19:16]), .HEX(HEX4));
  hexdriver hd5 (.val(io2[23:20]), .HEX(HEX5));
  hexdriver hd6 (.val(io2[27:24]), .HEX(HEX6));
  hexdriver hd7 (.val(io2[31:28]), .HEX(HEX7));

  cpu cpu_inst(.clk(CLOCK_50), .rst_n(KEY[0]), .io0_in({14'b0, SW[17:0]}), .io2_out(io2));

endmodule
